a=int(input('1st Integer:'))
b=int(input('2nd Integer:'))
print("Addition of {} and {} is {}".format(a,b,a+b))
print("Difference of {} and {} is {}".format(a,b,a-b))
print("Product of {} and {} is {}".format(a,b,a*b))
print("Division of {} and {} is {}".format(a,b,round(a/b,2)))
print("Modulus of {} and {} is {}".format(a,b,a%b))
